version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=chicago_business_intelligence
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - psql
    ports:
      - "5433:5432"

volumes:
  pgadmin_data:
  db-data: 

networks:
  psql:
    driver: bridge
